### ISSUE TITLE
(create new branch?) Add and stub out Run method from main to GameSpaceRunner Class in (new branch?)

### ISSUE THREAD

**Issue by lovittl** [lovittl/TeamExercise4#3]
not sure if I'm combining too many things here.  should I have you create a new branch to stub out the run() method?  I believe it should be called from main but live in GameSpaceRunner.  

P.S. maybe we should call it GSR for ease and change it in the project?? just thinking...

**Comment by NachoSourceCode** [comment]
closes #2   stub out class fields and methods.
